version: '3.8'

services:
  kairos:
    build: .
    container_name: kairos
    ports:
      - "8083:8083"
    volumes:
      - ./data:/app/data
      - ./digests:/app/digests
      - ./feeds.txt:/app/feeds.txt:ro
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8083/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
